/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205753;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AllElementsListTest {
    /**
     * allElementsに全てのリストが統合されているかを検証する。
     * 検証方法
     * 　（１）CreateListを生成。
     * 　（２）allElementsの要素数と12を比較。
     * 　（２）現在elements1~10に10、elements11~20に1、elements21~30に1つの要素があるため、allElementsには12の要素があると予想。
     */

    @Test
    void AllElementsTest(){
        int exseption = 12;
        CreateList test = new CreateList();
        assertEquals(test.getArrayAll().size(), exseption);

        
    }

}
